[workspace]
members = [
  "proxy",
  "proxy/convert",
  "proxy/controller-grpc",
  "proxy/futures-mpsc-lossy",
  "proxy/router",
]

[patch.crates-io]
prost-derive = { git = "https://github.com/danburkert/prost" }
